print("apple")
print("juice")
print("apple""juice")
print("apple", "juice")
print("apple","juice", sep= '~')
print("apple","juice", end= ' is ')
print("tasty")
input("what's your favorite juice? ")
print(input("what's your favorite juice? "))
